### ISSUE TITLE
Kubeflow on GCP - 1.5 release tracker

### ISSUE THREAD

**Issue by zijianjoy** [GoogleCloudPlatform/kubeflow-distribution#332]
TODO:

- [x] #346
- [x] Switch to use KFP manifest in kubeflow/pipelines repo, instead of personal repo
- [x] need to upgrade KFP due to https://github.com/kubeflow/pipelines/issues/7336
- [x] Install both KFserving and KServe, KServe 0.7 requires compatible istio and knative-serving versions: https://kserve.github.io/website/0.7/admin/serverless/
- [x] Use PACKAGE_DIR to find kptconfig folder when using yq.
- [x] #353
- [x] Consider changing to use `install_asm` CLI
- [x] Upgrade ASM version to be compatible with Kubernetes 1.22.
- [ ] No need to enable ASM independently https://www.kubeflow.org/docs/distributions/gke/deploy/project-setup/#set-up-project-and-api-scopes. https://cloud.google.com/service-mesh/v1.9/docs/gke-project-setup.
- [x] #341 
- [x] Fix pipeline cloudsqlproxy issue: spec.template.spec.containers[0].livenessProbe.httpGet.port: Invalid value: "8090": must contain at least one letter or number (a-z, 0-9)
- [x] #342
- [x] https://github.com/kubeflow/gcp-blueprints/issues/343

Others:

- Unfinished items in 1.4 release https://github.com/kubeflow/gcp-blueprints/issues/301
- Explore private cluster support: https://medium.com/dkatalis/installing-kubeflow-1-3-on-an-existing-and-private-gke-cluster-895283d49ed1
- Learn from Kubeflow/manifest approach to set up automated testing: https://github.com/kubeflow/manifests/tree/master/tests/e2e
- https://github.com/kubeflow/gcp-blueprints/issues/349
- Consider using profile controller to add labels for user created namespaces, then we can use label to distinguish user workload.
- Aim to use knative from kubeflow/manifests: https://github.com/kubeflow/manifests/tree/master/common/knative. Maybe require adjustment or kustomize v4 support. This update is for k8s 1.22 support: https://github.com/knative/serving/releases/tag/v0.22.3

**Comment by fakeskimo** [comment]
Hello, James! I am here.
