### ISSUE TITLE
Kubeflow on GCP - 1.6 release tracker

### ISSUE THREAD

**Issue by zijianjoy** [GoogleCloudPlatform/kubeflow-distribution#365]
### Kubeflow 1.5.1 patch release
- [x] https://github.com/kubeflow/gcp-blueprints/pull/364
- [x] #366
- [x] Upgrade to kubeflow upstream 1.5.1, and upgrade KFP upstream to 1.8.2.
- [x] Update documentation https://github.com/kubeflow/website/tree/master/content/en/docs/distributions/gke

### Kubeflow 1.6 release
- [x] Upgrade to kubeflow upstream 1.6, and upgrade KFP upstream to 2.0.0-alpha.3.
- [x] Upgrade knative based on https://github.com/kubeflow/manifests/issues/2207
- [x] Upgrade cert-manager based on https://github.com/kubeflow/manifests/issues/2207
- [x] #371
- [x] Upgrade metacontroller in [Manifests repository](https://github.com/kubeflow/manifests/tree/master/contrib/metacontroller)
- [x] Upgrade cloud-endpoints component
- [x] #360
- [x] #375
- [x] Migrate from [deprecated API in k8s v 1.22](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22) (#349)
- [x] Test on KF Manifests v1.6-rc.0
- [x] Test on KF Manifests v1.6-rc.1
- [x] Test on KF Manifests v1.6-rc.2
- [x] Test on KF Manifests v1.6.0
- [x] Update documentation https://github.com/kubeflow/website/tree/master/content/en/docs/distributions/gke
- [x] #385 
- [x] Change upstream of metacontroller to [kubeflow/pipelines](/kubeflow/pipelines)
- [x] Deprecate application resources in *contrib/application*
- [x] #384
- [x] #386
- [x] #376 
- [x] #377

## Others
- Explore using Porch from kpt: https://kpt.dev/guides/porch-installation
- https://github.com/kubeflow/gcp-blueprints/issues/332
