### ISSUE TITLE
Kubeflow on GCP - 1.7 release tracker

### ISSUE THREAD

**Issue by zijianjoy** [GoogleCloudPlatform/kubeflow-distribution#395]
## TODO

- [x] #405 
- [x] #404 
- [x] #406
- [x] #412
- [x] #408 
- [x] #407 
- [x] Test dependencies with newer versions (Kuberentes, istio, etc.)
- [x] No need to enable ASM independently https://www.kubeflow.org/docs/distributions/gke/deploy/project-setup/#set-up-project-and-api-scopes. https://cloud.google.com/service-mesh/v1.9/docs/gke-project-setup.
- [x] Explore IAP using commandline: http://cloud/iap/docs/programmatic-oauth-clients#known_limitations
- [x] #414

Reference: [Kubeflow 1.7 tracker](https://github.com/kubeflow/manifests/issues/2359)

## Others
- [ ] Explore using Porch from kpt: https://kpt.dev/guides/porch-installation
- [ ] Consider using profile controller to add labels for user created namespaces, then we can use label to distinguish user workload.
- [ ] Learn from Kubeflow/manifest approach to set up automated testing: https://github.com/kubeflow/manifests/tree/master/tests/e2e
- [ ] #399 
- Open items in https://github.com/GoogleCloudPlatform/kubeflow-distribution/issues/365
- Migrate to Kustomize v5
