### ISSUE TITLE
Kubeflow on Google Cloud - 1.7.1 release tracker

### ISSUE THREAD

**Issue by gkcalat** [GoogleCloudPlatform/kubeflow-distribution#423]
#TODO

Bugs/Issues to investigate:

- [x] #425
- [x] #421

Features to consider:
- [ ] Fix when GKE reaches version 1.27 #422
- [ ] Upgrade to Kustomize 5.0: fixes #402
- [ ] Learn from Kubeflow/manifest approach to set up automated testing: https://github.com/kubeflow/manifests/tree/master/tests/e2e
- [ ] Explore using Porch from kpt: https://kpt.dev/guides/porch-installation
- [ ] Consider using profile controller to add labels for user created namespaces, then we can use label to distinguish user workload.
- [ ] Migrate from Config Controller to Config Delivery

/CC @chensun @zijianjoy

**Comment by oguzhanoyan** [comment]
May asmcli error can be added also here, 

Issue detail; https://github.com/kubeflow/kubeflow/issues/7041#issuecomment-1491067102

Also, I have encountered the same issue and upgrading asmcli version fixed as I mentioned in above.

```
+ASM_PACKAGE_VERSION=1.14.6-asm.9+config1
+ASMCLI_SCRIPT_VERSION=asmcli_1.14.6-asm.9-config1
```

The latest tag is [1.17.2-asm.1+config1](https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/releases/tag/1.17.2-asm.1%2Bconfig1), Not sure whether working with 1.17.2 or not. But worked in 1.14.6-asm.9.

**Comment by gkcalat** [comment]
Kubeflow on Google Cloud 1.7.1 has been released: https://github.com/GoogleCloudPlatform/kubeflow-distribution/releases/tag/v1.7.1
