### ISSUE TITLE
Kubeflow on Google Cloud - 1.8.0 release tracker

### ISSUE THREAD

**Issue by Linchin** [GoogleCloudPlatform/kubeflow-distribution#438]
Bugs/Issues to investigate:
- [x] Test Kubeflow 1.8.0 on GCP
  - [x] deployment
  - [x] test pipeline run
  - [x] test notebook
  - [x] test KFP SDK 2.4
- [x] Test Kubeflow 1.8.0-rc.5 on GCP
  - [x] deployment
  - [x] test pipeline run
  - [x] test notebook
  - [x] test KFP SDK 2.4
- [x] Test Kubeflow 1.8.0-rc.2 on GCP
  - [x] deployment
  - [x] test pipeline run
  - [x] test notebook
- [x] Test Kubeflow 1.8.0-rc.1 on GCP
  - [x] deployment
  - [x] test pipeline run
  - [x] test notebook
- [x] Test Kubeflow 1.8.0-rc.0 on GCP
  - [x] deployment
  - [x] test pipeline run
  - [ ] ~~test notebook~~
- [x] https://github.com/GoogleCloudPlatform/kubeflow-distribution/issues/431
- [x] https://github.com/GoogleCloudPlatform/kubeflow-distribution/issues/440
- [x] https://github.com/kubeflow/pipelines/issues/10075

~~Features to consider (carry over from last release):~~
Out of scope:
- [ ] Fix when GKE reaches version 1.27 #422
- [ ] Upgrade to Kustomize 5.0: fixes #402
- [ ] #437
- [ ] Explore using Porch from kpt: https://kpt.dev/guides/porch-installation
- [ ] Consider using profile controller to add labels for user created namespaces, then we can use label to distinguish user workload.
- [ ] Migrate from Config Controller to Config Delivery
- [ ] Explore upgrading [controller tool version](https://github.com/kubeflow/kubeflow/blob/194a725119e9bf8a16db37a1d23f0e941ab7f1e4/components/profile-controller/Makefile#L140) 
- [ ] Explore using Terraform to enable GCP services instead of using management cluster.

/CC @chensun @zijianjoy @gkcalat

**Comment by chensun** [comment]
Not sure how we marked notebook as tested. It seems there's a authentication issue from the SDK implementation that would block any SDK interaction with the pipeline from a Notebook environment.
https://github.com/kubeflow/pipelines/issues/10075
